name: Destroy kitchen on demand

on:
  issues:
    types:
      - labeled

jobs:
  terraform-destroy:
    name: Destroy Azure Resources using Terraform
    if: github.event.label.name == 'destroy'
    runs-on: ubuntu-20.04

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Retrieves the Terraform CLI used in the GitHub action workflow
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initializes Terraform configurations.
      - name: Terraform Init
        run: terraform init

      # Destroys terraform configuration
      - name: Terraform Destroy
        run: terraform apply -destroy -auto-approve
