name: Create kitchen

on:
  push:
    branches: [main]
    paths:
      - "development/**"

jobs:
  # Apply Infrastructure configurations when action=='create'.
  create:
    name: Create resources
    uses: nmbrs/demo-gh-reusable-workflows/.github/workflows/terraform-create.template.yaml@main
    with:
      target-directory: development
    secrets:
      key_vault_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME }}
