name: Destroy kitchen at the end of the day

on:
  schedule:
    # Triggers every day at 19:00
    - cron:  '0 19 * * *'


jobs:
  # Destroy Infrastructure configurations when a issue is labelled as "destroy".
  destroy-kitchen:
    name: Destroy kitchen resources
    if: github.event.label.name == 'destroy'
    uses: ./.github/workflows/terraform-destroy.template.yaml
    with:      
      secrets_keys_list: 'terraformApiToken'
    secrets:
      key_vault_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME }}