name: Create / destroy resources manually

on:
  workflow_dispatch:
    environment:
      description: "Deployment environment (development/production/staging)"
      required: false
      type: string
      default: "development"

jobs:
  # Apply Infrastructure configurations when a change is pushed to default branch.
  create:
    name: Create resources
    if: ${{ github.event.inputs.action == 'create' }}
    uses: ./.github/workflows/terraform-create.template.yaml
    with:
      target-directory: ${{ github.event.inputs.environment }}
    secrets:
      key_vault_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME }}

  # Apply Infrastructure configurations when a change is pushed to default branch.
  destroy:
    name: Destroy resources
    if: ${{ github.event.inputs.action == 'destroy' }}
    uses: ./.github/workflows/terraform-destroy.template.yaml
    with:
      target-directory: ${{ github.event.inputs.environment }}
    secrets:
      key_vault_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME }}
