name: Create kitchen manually

on:
  workflow_dispatch:
    inputs:
      service-name:
        description: "Service name"
        required: true
        type: string
      environment:
        description: "Deployment environment (dev/prod)"
        required: false
        type: string
        default: "dev"

jobs:
  # Apply Infrastructure configurations when a change is pushed to default branch.
  create-kitchen:
    name: Create kitchen resources
    uses: ./.github/workflows/terraform-create.template.yaml
    with:
      secrets_keys_list: "terraformApiToken"
      service-name: ${{ github.event.inputs.service-name }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      key_vault_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME }}
